spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:mysql://${MYSQL_HOSTNAME}/thealley?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

thealley:
  mqtt:
    host: ${MQTT_HOST}
    user: ${MQTT_USER}
    pass: ${MQTT_PASS}
  relay:
    apiKey: ${RELAY_API_KEY}
  tado:
    refreshToken: ${TADO_KEY}

clients.clients:
  - clientId: google
    secret: ${GOOGLE_SECRET}
    scopes:
      - "read"
      - "write"
