spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:mysql://${MYSQL_HOSTNAME}/thealley?autoReconnect=true&useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

thealley:
  relay:
    apiKey: ${RELAY_API_KEY}
  tado:
    refreshToken: ${TADO_KEY}

logging.level.org.springframework.security: DEBUG

clients.clients:
  - clientId: google
    secret: ${GOOGLE_SECRET}
    scopes:
      - "read"
      - "write"
